### ISSUE TITLE
Brak możliwości szybkiego wysunięcia menu

### ISSUE THREAD

**Issue by dobrzecisiewydaje** [CodoDodo/Zakop#10]
Zeby dostac się do menu trzeba wracać przez wszystkie otwarte odnośniki. Fajnie by było zrobić wysuwaną belke, po przejechaniu od połowy ekranu w prawo lub coś w tym stylu.

**Comment by CodoDodo** [comment]
Nie wiem czy to zmienimy, taki gest kolidowałby z gestem powrotu (ten z przeciągnięciem od lewej krawędzi ekranu), a sama nawigacja jest tak przemyślana, aby przypadkowo nie była zapętlana w koło.

Przeprowadzimy ankietę na mikroblogu gdzie spytamy co zrobić z nawigacją i ilu osobom ona przeszkadza a ilu odpowiada. Zawsze można dodać opcję do zmiany w ustawieniach :) Tutaj raczej potrzebny jest głos więkości

**Comment by dobrzecisiewydaje** [comment]
Nie musi kolidować. Od krawędzi ekranu powrót, od środka menu. 

https://gfycat.com/pl/decentverifiablekittiwake

**Comment by CodoDodo** [comment]
@dobrzecisiewydaje Czy obecny widok z zakładkami na dole bardziej Ci odpowiada niż wysuwane menu? Bo obecnie zastanawiamy się co z tym tematem dalej zrobić :) Którą wersję wolisz? 
Obecnie chyba większość preferuje ten styl, mniej ten z jednym menu i bez paska na dole

**Comment by dobrzecisiewydaje** [comment]
Tak! Jest super!
