### ISSUE TITLE
Ekran ładowania: w tle same linie

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#101]
Prio: normalny

Czy na 100% wtedy, kiedy wyświetla się loader, musi być pod spodem tabela? Słabo to wygląda.
![1a3cb5d2-5e5b-4cc7-8f52-c10519583ed3](https://user-images.githubusercontent.com/45828761/49894073-4f3af180-fe4d-11e8-9d63-31a898be59d8.png)

**Comment by CodoDodo** [comment]
Poprawione
