### ISSUE TITLE
Nie widać czy dany wpis został przez siebie zaplusowany

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#103]
Prio: normalny

Nie da się na pierwszy rzut oka rozróżnić czy dany wpis został przez nas zaplusowany czy też nie. To wiemy dopiero po przesunięciu w lewo albo po przytrzymaniu wpisu palcem. Ain’t nobody got time for that ( ͡° ͜ʖ ͡°)

**Comment by CodoDodo** [comment]
Poprawione, zmiana będzie dostępna w następnej aktualizacji
