### ISSUE TITLE
Brak wyróżnienia naszych wpisów/komentarzy

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#105]
Prio: normalny

W gąszczu komentarzy nie mam na czym zawiesić wzroku by widzieć, że to jest mój komentarz.
Może jakiś kolor wyróżnika na lewym pasku, tak jak OP ma wyróżnik pomarańczowy.
![402dcbe8-6f9a-41fc-b6a2-b616c5f59482](https://user-images.githubusercontent.com/45828761/49896747-97a9dd80-fe54-11e8-8fe9-3fa4a8cb8dbd.png)

**Comment by CodoDodo** [comment]
Jest to już dodane w nadchodzącej wersji w ten sam sposób właśnie :)
