### ISSUE TITLE
Linie tabeli po dodaniu wpisu

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#106]
Prio: normalny

Brzydki widok linii tabeli po dodaniu nowego wpisu :/
![63e912fb-2975-47d2-b9ad-f83f73c4127c](https://user-images.githubusercontent.com/45828761/49897051-582fc100-fe55-11e8-910b-99c29c4f0387.png)

**Comment by CodoDodo** [comment]
Duplikat https://github.com/CodoDodo/Zakop/issues/87 i https://github.com/CodoDodo/Zakop/issues/101
