### ISSUE TITLE
POMYSŁ: Dwukrotne tapnięcie plusuje

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#107]
Podczas klikania wpadłam na pomysł jaki jest zaimplementowany na Instagramie. Tam dwukrotne tapnięcie na zdjęciu powoduje polubienie zdjęcia.
Na mirko dwukrotne tapnięcie wpisu/komentarza mogłoby spowodować zaplusowanie : D
A ponowne dwukrotne tapnięcie - odplusowanie.

**Comment by CodoDodo** [comment]
Dobry pomysł, aaaaaale:
- Mamy zbyt duzo klikalnych elementów na wykopie - obrazki, linki, tagi, awatar też jest klikalny... Może być problematyczne wykonanie takiej akcji
- W kolejnej wersji mamy już coś podobnego, tyle że na samych plusach :) Klik plusuje/odplusowuje a dwuklik minusuje/odminusuwuje :)
