### ISSUE TITLE
Przesunięcie palcem w górę nie powoduje odświeżenia strony

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#108]
Prio: wysoki

W długim wątku, gdy jesteś na dole strony, chciałbyś zaktualizować najnowsze komentarze - co robisz?

Moim odruchem było przesunięcie palcem w górę a to nie odświeża strony :(

**Comment by CodoDodo** [comment]
@Hannahalla Fajny pomysł, ale po przemyśleniach nie dodamy go z kilku powodów:

- Przy wpisie, który ma tylko jeden komentarz albo jest pusty, odświeżanie będzie bardzo dziwnie wyglądać
- Dodaliśmy w nowej wersji ikonę odśwież na górnym pasku
- Na dole przy listach pojawiają się w tym miejscu inne informacje jak np. brak połączenia albo właśnie taki progres z ładowaniem kolejnej strony (który nie jest gestem) i problematycznym jest obsługa obu jednocześnie.
