### ISSUE TITLE
Podwójne rozwijanie wpisu

### ISSUE THREAD

**Issue by xadereq** [CodoDodo/Zakop#111]
Rozwinięty wpis po wejściu na niego powinien być nadal rozwinięty.
Reprodukcja:
1. rozwijamy wpis,
2. klikamy we wpis żeby do niego przejść,
3. treść wpisu jest znowu zwinięta

**Comment by CodoDodo** [comment]
@xadereq Nie poprawimy tego bo nie widzimy za bardzo sensu - jeżeli ktoś już rozwinął wpis to raczej go przeczytał, a gdy taki wpis jest długi to podczas otwierania komentarzy musimy przewijać dużo tekstu. Jest to szczególnie widoczne w np. #anonimowychmirkowyznaniach gdzie takie coś jest strasznie irytujące. 

Jeżeli będzie więcej tego typu próśb to może dodamy odpowiednią opcję w ustawieniach, ale na obecną chwilę nie planujemy dodania takiej opcji.
