### ISSUE TITLE
Rozmiar GIF + anulowanie buforowania

### ISSUE THREAD

**Issue by xadereq** [CodoDodo/Zakop#113]
Dość ważną sprawą jest umieszczenie w którymś miejscu wagi GIFa. Przy pakiecie 1-2GB wystarczy się nadziać kilka razy na GIFy o rozmiarze 20MB i można pożegnać się z pakietem.
Oprócz tego byłoby super jeśli po otworzeniu GIFa(który się dość długo ładuje bo mamy slaby zasięg/GIF dużo zajmuje) jego pobieranie by zostało anulowane po wyjściu do widoku wpisu/wpisów.

**Comment by CodoDodo** [comment]
Dodane i poprawione, oczekuj akutalizacji dzisiaj :-)
