### ISSUE TITLE
Brak zakładki Aktywne na Mikro

### ISSUE THREAD

**Issue by dobrzecisiewydaje** [CodoDodo/Zakop#12]
Mamy teraz tylko domyślne sortowanie od najnowszych albo trzy przedziały czasowe Gorących

**Comment by CodoDodo** [comment]
@dobrzecisiewydaje  Nie zauważyliśmy, że jest trzecia kategoria, trafna uwaga :)

**Comment by CodoDodo** [comment]
Poprawione
