### ISSUE TITLE
Funkcja 'Pokaż tylko plusowane wpisy'

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#121]
Przy wyłączaniu tej funkcji w menu przydałoby się gdyby tekst zmieniał się na na przykład "Pokaż wszystkie wpisy". Teraz zostaje tak czy inaczej "Pokaż tylko plusowane wpisy"

**Comment by Cideu** [comment]
@CodoDodo 2. Funkcja pojawia się też w widoku pojedynczego wpisu na mirko. Chyba niepotrzebnie(?) bo i tam nie działa.

2a. Zdublowany przycisk odświeżania (w menu i w górnym rogu)

![img_2318](https://user-images.githubusercontent.com/44524082/50302757-56847f80-048b-11e9-9c09-2c420e55c18e.jpg)

**Comment by CodoDodo** [comment]
Poprawione x3
