### ISSUE TITLE
Niewyrównane ikony w dolnym pasku

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#122]
iPhone X, przy 5 ikonach nie wyglada to dobrze. Ikonki nie maja równej odległości od siebie. Przy 4 jest ok. Przy 3 również nie równo. Pierwsza ikona ma za duży lewy margines.

https://i.imgur.com/G27oZrq_d.jpg
https://i.imgur.com/1VtFfSa_d.jpg

**Comment by CodoDodo** [comment]
@RichForever To raczej złudzenie optyczne, ten element iOS domyślnie tak wyświetla te elementy i pewnie przez różną długość tekstów masz wrażenie, że jeden element nie jest równy.

Dodamy opcję ukrycia napisów i może to będzie CI bardziej odpowiadać :)

**Comment by CodoDodo** [comment]
Dodane a ikonka została lekko powiększona aby zniwelować efekt
