### ISSUE TITLE
Limit zapytań został wykorzystany

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#123]
Ups… teraz to już zepsułem 😳
![img_2319](https://user-images.githubusercontent.com/44524082/50303199-9f890380-048c-11e9-80d5-05fc540fb2a2.png)

**Comment by CodoDodo** [comment]
@Cideu Coś Ty tam wyklikał? :P

**Comment by CodoDodo** [comment]
@Cideu Jeden raz? Czy wchodziłeś w rozmowę?

**Comment by Cideu** [comment]
@CodoDodo W kolejne okna rozmowy, próbując wczytać wcześniejsze wiadomości.

**Comment by CodoDodo** [comment]
@Cideu OK zobaczymy, może coś się zapętla i jest taki jest efekt

**Comment by Cideu** [comment]
@CodoDodo I się powtórzyło. Co dziwne przy całkiem normalnym użytkowaniu, bez szalonego klikania 🤔 Dodatkowo przy próbie ponownego zalogowania: 
![img_2321](https://user-images.githubusercontent.com/44524082/50305986-aa479680-0494-11e9-811c-52d3ae9e8749.png)

**Comment by CodoDodo** [comment]
@Cideu W razie kolejnego powtórzenia prosimy o otwarcie nowego tematu :-)
