### ISSUE TITLE
Gfycat - zamknięcie okna gestem

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#125]
Czy istnieje możliwość zamknięcia otwartego okna z gfycatem gestem tak jak obrazek? Natywny swipe z iOS z góry do dołu?

**Comment by CodoDodo** [comment]
Tak, zrobiliśmy ten moduł tak naprawdę na szybko i w ostatnim momencie, ale da sie jak najbardziej.

**Comment by CodoDodo** [comment]
Poprawione!
