### ISSUE TITLE
Obserwuj/zablokuj tag - brak reakcji przycisków

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#126]
Przyciski zablokuj/obserwuj po wejściu w tag nie reagują na przyciśnięcie. Dodatkowo nie działa w nich customowy akcent. Mimo wyboru np. pomarańczowego ikony obserwuj/zablokuj nadal są niebieskie.

**Comment by CodoDodo** [comment]
@RichForever Tak jak napisaliśmy na wykopie, jeszcze tego nie obsługujemy

**Comment by RichForever** [comment]
@CodoDodo ok, moje niedopatrzenie :)

**Comment by CodoDodo** [comment]
@RichForever Dodaliśmy blokowanie użytkowników i tagów, poprawka będzie w kolejnej aktualizacji :)
