### ISSUE TITLE
Zmiana koloru akcentu - błąd odświeżania interfejsu

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#128]
Wszystko widać na filmiku. Dodatkowo opcja pomimo, że jest premium to mogę w nią wejść nie mając owego premium.
iPhone X, iOS 12, najnowsza wersja apki

https://streamable.com/189gs

**Comment by Cideu** [comment]
@CodoDodo Potwierdzam. Problem również występuje przy przełączaniu nocny/dzienny za pomocą nowego gestu. Zachowanie analogiczne jak w #64

**Comment by CodoDodo** [comment]
Poprawione x2

**Comment by RichForever** [comment]
@CodoDodo już prawie, ale zostały małe poprawki :D Przy przełączaniu trybów poprzez przytrzymanie przycisku pojawia się taki babol

https://streamable.com/3yvu5
