### ISSUE TITLE
Licznik powiadomień w widoku poziomym

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#129]
Licznik powiadomień w widoku poziomym wydaje się trochę za wysoko umiejscowiony.

![img_2320](https://user-images.githubusercontent.com/44524082/50305005-eaf1e080-0491-11e9-96ea-3538e16a0c5a.png)

**Comment by CodoDodo** [comment]
Duplikat https://github.com/CodoDodo/Zakop/issues/92
