### ISSUE TITLE
Brak dostosowania do gestów przy odświeżaniu treści 

### ISSUE THREAD

**Issue by dobrzecisiewydaje** [CodoDodo/Zakop#13]
Jak w oficjalnej apce - przesunięcie treści w dół powoduje odświeżenie. W przypadku skończonych wątków (np. prywatne wiadomości albo konkretny wątek na mikro) może to być przesunięcie w dowoloną stronę (góra - dół). Dużo wygodniejsze niż klikanie z opcji.

**Comment by CodoDodo** [comment]
@dobrzecisiewydaje Czyli brakuje Ci "Pull to refresh" oraz gestów przy postach?
Do dyskusji w https://github.com/CodoDodo/Zakop/issues/20

**Comment by CodoDodo** [comment]
Dodano w wersji z numerem 5.
