### ISSUE TITLE
Błąd wygaszania w trybie bezczynności

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#132]
W oficjalnej apce jeżeli nie scrolluje, klikam itd. ekran wygasza się po ilus tam sekundach (zakładam ze tyle ile mam ustawione dla całego systemu). W zakopie natomiast ekran pali się non stop mimo bezczynności. Poprawcie proszę  asap bo można się zdziwić jak bateria się nagle wyczerpie :D
Używam najnowszej wersji beta

**Comment by CodoDodo** [comment]
Używałeś być może czytania z Siri?

**Comment by RichForever** [comment]
Próbowałem użyć tej opcji, ale mi nie zadziała z tego co pamietam. No i było to raz, zanim zauważyłem błąd.

**Comment by CodoDodo** [comment]
@RichForever No nic, daj znać czy błąd będzie się powtarzał po następnej aktualizacji

**Comment by RichForever** [comment]
@CodoDodo wygląda na to, że problem został rozwiązany ;)
