### ISSUE TITLE
Odtwarzacz

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#133]
1. Czy możecie zrobić tę większą wersję przycisków pauza/play i przewijania w odtwarzaczu?
 
![img_2333](https://user-images.githubusercontent.com/44524082/50384713-cd5a8c00-06c8-11e9-84ee-805378fbdbc0.jpg)

2. Czy da się te elementy youtub'a wyłączyć? (Do obejrzenia, Udostępnij, Więcej filmów).
 Teraz zasłaniają systemową regulację głośności. W poziomie również zasłaniają przycisk Zamknij

![img_2334](https://user-images.githubusercontent.com/44524082/50384752-5ec9fe00-06c9-11e9-942f-ed9a475bdd37.jpg)

3. Czy możliwe jest wyłączanie video gestem w dół? Tak jak zdjęcia

**Comment by CodoDodo** [comment]
Postaramy się poprawić, ale nie wiem czy w kolejnej wersji - ona będzie poświęcona blokowaniu tagów i profilów

**Comment by RichForever** [comment]
@CodoDodo @Cideu co do pkt 2 i 3 to się zgadzam. Ale pkt 1 zostawiłbym jak jest. Obstawiam, że to systemowa nakładka i jak dla mnie sprawdza się idealnie. Ew może powiększenie ikon dodać jako opcja premium?

**Comment by CodoDodo** [comment]
@RichForever @Cideu 
Używamy teraz w pełni systemowego odtwarzacza, więc i są przyciski i brak tytułów i innych przeszkadzaczy :-) Aktualizacja wkrótce
