### ISSUE TITLE
Mój wykop - błąd odświeżania

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#134]
Zakop nie zawsze odświeża poprawnie posty w zakładce mój wykop. Wydaje mi się, że problemem jest przycisk w prawym górnym rogu. Na filmiku widok mojego wykopu w oficjalnej apce. Jak widać posty wczytują się przy scrollowaniu. W zakop, na początku jest ok. Po odświeżeniu lista kończy się w pewnym momencie i dalsze wpisy się nie wczytują. Dopiero kill aplikacji pomaga. Do czasu odświeżenia

https://streamable.com/subd9

@edit
Błąd występuje również przy przeglądaniu tagów

**Comment by CodoDodo** [comment]
Poprawione!
