### ISSUE TITLE
„Migające” tło przycisku czytaj dalej

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#137]
Tryb nocny, OLED. Przy scrollowaniu tło przycisku dostaje dziwnej animacji. Tak jakby tło pod spodem falowalo. Póki co zauważyłem tylko w przypadku „czytaj dalej” w znalezisku. Do sprawdzenia czy w innych przyciskach tez to występuje. Poniżej wideo

https://streamable.com/9u8vc

**Comment by CodoDodo** [comment]
Czy przypadkiem nie posiadasz iPhone X/XS? To raczej wada OLEDów, które przy szybkich ruchach obiektów z dużym kontratem tworza taka smugę https://www.youtube.com/watch?v=wnAi6TPdgeg

**Comment by RichForever** [comment]
@CodoDodo fakt, używam iPhone X. Nie było tematu w takim razie :)
