### ISSUE TITLE
Gfycat zatrzymuje odtwarzaną muzykę

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#140]
iPhone X, najnowsza beta z 4.01.2019

Słucham sobie muzyki, np. na spotify. Wchodzę w gfycata - muzyka w spotify się zatrzymuje. No więc wchodzę w spotify, daje play. Wracam do zakop i... spotify znowu się stopuje :D Pomaga jedynie ubicie aplikacji. Problem poniżej, na filmiku

https://streamable.com/wu6ii

**Comment by CodoDodo** [comment]
Poprawione
