### ISSUE TITLE
Skomentowane znaleziska - nieobsługiwany URL / propozycja zmiany

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#141]
Po wejściu w link "Skomentowane znaleziska" i kliknięciu w ikonę w prawym górnym rogu pojawia mi się opcja wyboru. Główna albo hity. Cokolwiek bym nie wybrał dostaję error
"wystąpił błąd - nieobsługiwany URL"

Generalnie proponowałbym zmianę działania tego modułu. Otóż zrobić z niego "komentarze", a w rodzajach dodać mikroblog albo główna. Oczywiście to luźna propozycja :)

**Comment by CodoDodo** [comment]
Bug poprawiony.
Co do drugiej części to zamierzaliśmy dodać zakładkę, która tak działa, ale Wykop coś popsuł i zwraca ona te same dane co "Skomentowane znaleziska". Musimy poczekać na poprawę tego błędu.
