### ISSUE TITLE
Znaleziska z płomieniem 

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#145]
Przydałoby się jakieś oznaczenie znaleziska, które dostało się na główną z płomieniem. 

Edit: to jednak błąd, nie wyświetlają mi się płomienie na stronie głównej, tylko w stronie hity

**Comment by CodoDodo** [comment]
Mówimy o listach czy szczegółach? Bo w tym pierwsyzm wypadku jest już takie oznaczenie:
![simulator screen shot - iphone 6 - 2019-01-05 at 13 02 30](https://user-images.githubusercontent.com/44480523/50724222-4fe04400-10ea-11e9-9550-b45fa06ef8d4.png)
