### ISSUE TITLE
Przycisk w menu głównym

### ISSUE THREAD

**Issue by pankara** [CodoDodo/Zakop#147]
Odpalając aplikację w górnym rogu mamy przycisk Edytuj / Gotowe który nie robi totalnie nic albo robi i nie działa. W trybie edycji nie da się usuwac, przesuwac, edytowac zadnych rzeczy na ekranie.

Dodatkowo w trybie edycji, nie da się wejść w żaden z linków. 

Iphone 6s
Ios 12.1.2

![img_3241](https://user-images.githubusercontent.com/46407694/50729750-649af700-113f-11e9-8f69-18c3eab9d0e6.PNG)
![img_3240](https://user-images.githubusercontent.com/46407694/50729751-649af700-113f-11e9-89be-dea3c4208f8e.PNG)

**Comment by CodoDodo** [comment]
Robi robi, tylko nie masz żadnych szybkich linków dodanych aby było widać zmiany ;)
Dodamy komunikat co trzeba zrobić gdy takowych nie ma.

**Comment by CodoDodo** [comment]
Poprawione
