### ISSUE TITLE
iPad - margines

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#149]
Co myślicie nad dodaniem, trochę większych marginesów od lewego i prawego brzegu dla treści w apce na iPadzie? Tak, jak jest w Apollo.

**Comment by CodoDodo** [comment]
Mamy zamiar przygotować osobną wersję na iPada. 
Jest już nawet otwarty wątek na ten temat https://github.com/CodoDodo/Zakop/issues/100. 

Marginesów póki co nie będziemy zmieniać skoro planujemy mieć i tak inny wygląd dla iPada niż ten iPhoneowy.
