### ISSUE TITLE
Cofnij wpisywanie

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#152]
Nieczytelny kolor w trybie nocnym
![img_2374](https://user-images.githubusercontent.com/44524082/50891024-ace63d80-13fb-11e9-9de3-81e17bc71173.jpg)

**Comment by CodoDodo** [comment]
Skad ten komunikat? Czy to po potrzasaniu telefonem? Jest on chyba
systemowy i nic w nim nie mozemy zmienic :( Sprawdzimy.

**Comment by Cideu** [comment]
@CodoDodo Tak, cofanie po potrząśnięciu

**Comment by CodoDodo** [comment]
Poprawione :-)
