### ISSUE TITLE
'Dodaj nowy wpis' w trybie nocnym

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#153]
W trybie nocnym z przyciskiem 'Dodaj nowy wpis' dzieje się coś dziwnego. Tak jakby przy przesuwaniu w dół jego tło pływało. Co dziwne nie widać tego na nagraniu... https://imgur.com/a/E8XgLpx

**Comment by CodoDodo** [comment]
To ten sam efekt co tutaj: https://github.com/CodoDodo/Zakop/issues/137 
Ekrany OLED wyświetlają takie smużenie gdy kontrast jest wysoki.
