### ISSUE TITLE
Akcje w profilu

### ISSUE THREAD

**Issue by pankara** [CodoDodo/Zakop#157]
W niektorych akcjach profilu brakuje liczby akcji
![img_3243](https://user-images.githubusercontent.com/46407694/50934851-3cc2d080-146a-11e9-9b86-2ff0159343f0.PNG)

**Comment by CodoDodo** [comment]
Tego niestety nie damy rady poprawić :( Wykop.pl nie przekazuje nam niektórych danych (jak np. liczba odznaczeń) i nie mamy skąd tej liczby wziąć (przed wejściem w wybrane dane)
