### ISSUE TITLE
Odswiezanie plusow

### ISSUE THREAD

**Issue by pankara** [CodoDodo/Zakop#159]
Jesli zaplusujemy wpis np w goracych i wejdziemy we wpis, liczba plusow sie zmniejsza oraz znika oznaczenie plusa we wpisie
![img_3250](https://user-images.githubusercontent.com/46407694/50934752-e8b7ec00-1469-11e9-843c-331bb080aecd.PNG)
![img_3249](https://user-images.githubusercontent.com/46407694/50934753-e8b7ec00-1469-11e9-8fa1-7ce8c793fe99.PNG)

**Comment by CodoDodo** [comment]
W tym przypadku musiał wystąpić jakiś błąd API i plus został niezaliczony. Dziwne, że nie pokazał się żaden komunikat błędu bo to obsługujemy w tym przypadku.
