### ISSUE TITLE
Okno dodawania wpisu.

### ISSUE THREAD

**Issue by pankara** [CodoDodo/Zakop#161]
Ok, może jest to nieaktualne, ze względu na zmiane lokalizacji, a moze dalej aktualne. 
Po zmniejszeniu wpisu, dostajemy bardzo nieintuicyjny popup na dole ekranu.

Widoczne sa przyciski opublikuj i anuluj ale działa tylko środkowy guzik nawigacji. Czy można dodać featura żeby owe guziki były "clickable" albo je ukryc ew w jakis sposob wyszarzyć tak jak nieaktywne jsowe guziki na webie?

![img_3245](https://user-images.githubusercontent.com/46407694/50935125-4a2c8a80-146b-11e9-81f6-402fc5ff23d1.PNG)

**Comment by CodoDodo** [comment]
Poprawione

**Comment by CodoDodo** [comment]
Poprawione :)
