### ISSUE TITLE
Instagram i Twitter do wpisu

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#164]
Nie da się dodać do wpisu ramki z instagrama i twittera za pomocą linka (jak to jest na stronie www). Wyskakuje komunikat o błędnym odnośniku.

**Comment by RichForever** [comment]
@Cideu dubelek #118

**Comment by Cideu** [comment]
@RichForever tam było tylko wyświetlanie, tu jest problem z zamieszczaniem takich ramek

**Comment by CodoDodo** [comment]
@Cideu @RichForever 
Oznaczymy jako duplikat tak czy inaczej.

Postaramy się dodać odpowiednie ramki jeżeli to będzie możliwe, co do postowania to zobaczymy bo API Wykopu często ma swoje humorki ;-)
