### ISSUE TITLE
Kopiowanie tekstu

### ISSUE THREAD

**Issue by xadereq** [CodoDodo/Zakop#165]
Wydaje mi się że wielu osobom przydała by się możliwość kopiowanie tekstu wpisu/komentarza.
Dodatkową funkcjonalnością byłoby kopiowanie tekstu z lub bez spoilerów.

**Comment by RichForever** [comment]
@CodoDodo przydałoby się ;)

**Comment by CodoDodo** [comment]
Duplikat https://github.com/CodoDodo/Zakop/issues/227
