### ISSUE TITLE
Brak tekstu na popupach(?)

### ISSUE THREAD

**Issue by pankara** [CodoDodo/Zakop#170]
![fad35e41-7328-46ff-8a84-afdc3b5c0a9f](https://user-images.githubusercontent.com/46407694/51322038-a04d8f00-1a64-11e9-9a9a-9952ec3233e0.png)
![5ac12113-aa31-4e33-b52a-255d2428955d](https://user-images.githubusercontent.com/46407694/51322039-a04d8f00-1a64-11e9-8b32-f89477ae22f2.png)

Cos sie niedociaga. Przy edycji, przy wyszukiwania usera, tak jak na screenach

**Comment by CodoDodo** [comment]
Poprawione w nowej wersji.
