### ISSUE TITLE
Nowe logowanie

### ISSUE THREAD

**Issue by michalw1987** [CodoDodo/Zakop#171]
Codziennie gdy uruchamiam aplikacje przychodzi mi powiadomienie na maila o nowym logowaniu. Wcześniej ten problem nie występował

**Comment by michalw1987** [comment]
Dodam że dzieje się tak od 12 stycznia

**Comment by pankara** [comment]
#duplikat

**Comment by CodoDodo** [comment]
@michalw1987 jak @pankara napisał, duplikat. O tym temacie rozmawiamy tutaj https://github.com/CodoDodo/Zakop/issues/166
