### ISSUE TITLE
Kierunek wpisywania tekstu w oknie PW

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#178]
Pisząc wiadomość pw tekst przesuwa się w prawo. Pole do wpisania jest dość małe. Propozycja - powiększyć (więcej wierszy) okno do wpisywania wiadomości. A tekst, który się nie mieści w oknie niech przesuwa się góra-dół a nie prawo-lewo.

**Comment by RichForever** [comment]
Odświeżam. Pisanie dłuższych wiadomości w tym momencie jest na maksa niewygodne. Jest szansa na szybkie wprowadzenie tej poprawki?
@CodoDodo

**Comment by CodoDodo** [comment]
@RichForever Postaramy się to poprawić dzisiaj :-)

**Comment by CodoDodo** [comment]
Dodane i poprawione
