### ISSUE TITLE
Niewidoczny znacznik zmniejszania okna odpowiedzi

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#182]
Tryb OLED. Wskaźnik minimalizacji okna komentarza jest niewidoczny. Może (jeżeli się da) zrobić go w kolorze białym albo wybranego akcentu? Chodzi o ten na samej górze pomiędzy „anuluj” a „opublikuj”

**Comment by CodoDodo** [comment]
Poprawione
