### ISSUE TITLE
Brak formatowania cytowanego tekstu, gdy wpis jest długi

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#184]
Gdy wpis jest dłuższy i pojawia się opcja "Czytaj dalej", to znika formatowanie cytatu, czyli taki tekst jest wyświetlany normalnie:
![img_0031](https://user-images.githubusercontent.com/23238398/52499448-bc63cc80-2bdb-11e9-8e2c-0dd70fab7363.PNG)
Drugi akapit jest cytatem.

**Comment by CodoDodo** [comment]
Poprawione
