### ISSUE TITLE
Przełączenie między trybem nocny / dzienny

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#187]
Przełączenie między trybami nocny / dzienny za pomocą skrótu na ikonie w menu nawigacji działa powoli. To samo z menu nawigacji. Widać, że elementy ładują się dużo wolniej, a haptic feedback wchodzi z ok. sekundowym opóźnieniem.

**Comment by CodoDodo** [comment]
Przełączanie motywów trwa chwilę, bo system ma dużo elementów do zmiany w jednym czasie. 
Wibracja natomiast posiada opóźnienie, bo sytem musi najpierw przygotować silniczek do pracy, a następnie go uruchomić. Dochodzą do tego jeszcze stany uśpienia opisane tutaj: https://developer.apple.com/documentation/uikit/uifeedbackgenerator/2369818-prepare
