### ISSUE TITLE
Error w wyszukiwarce podaje zbyt dużo informacji

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#189]
1. Otwórz Menu
2. Wybierz opcję Użytkownik/Tag
3. Wpisz polską literę (np. 'ą')
4. Kliknij OK.

Dostajemy komunikat o niepoprawnym linku, wraz z jego zawartością, która zdradza klucz API (wycięty ze zdjęć)!
![img_0050](https://user-images.githubusercontent.com/23238398/52533500-f1cffd80-2d34-11e9-8c22-2ccfa7c86a22.PNG)
![img_0052](https://user-images.githubusercontent.com/23238398/52533502-f4325780-2d34-11e9-9f76-8f9c92a7b61f.PNG)

**Comment by JonahKK** [comment]
Błąd dalej występuje, w nowej wersji wyszukiwarki.

**Comment by CodoDodo** [comment]
Poprawione
