### ISSUE TITLE
Brak przyciskow "+" i "-"

### ISSUE THREAD

**Issue by Ciema** [CodoDodo/Zakop#19]
Przydalyby sie te przyciski (takie male) pod kazdym wpisem/komentarzem zamiast otwierania menu "Akcje".

**Comment by CodoDodo** [comment]
Same przyciski do dyskusji w temacie zmian UI tutaj: https://github.com/CodoDodo/Zakop/issues/20.
Opcje do minusowania dodamy wkrótce, usuwanie plusów jest dostępne na mikroblogu więc pozostają tylko linki.
