### ISSUE TITLE
Gfycat - nie działa po pewnym czasie

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#190]
Jak w tytule. Po pewnym czasie filmy gfycat nie działają. Mamy loopa z animacja ładowania. Pomaga tylko ubicie aplikacji. Niestety nie jestem w stanie stwierdzić czy to działanie spowodowane jest czymś konkretnym, czy jakimś dłuższym stanem bezczynności :/

**Comment by tejotte** [comment]
W moim przypadku ubicie aplikacji nie pomaga. Mam tak od poczatku wersji beta ale z lenistwa nie zgłaszałem licząc na poprawę przed releasem. 

Przykładowy gfy, który nie działa: https://www.wykop.pl/wpis/38892673

**Comment by CodoDodo** [comment]
@RichForever @tejotte 
Z tego co zauważyliśmy to Wykop zmienił zwracanie linków z gfycata, albo sam gfycat zaczął rozróżniać wielkość znaków w ich mediach. Spójrzcie na link przed odtwarzaniem i po - różnią się od siebie i tutaj pojawia się problem, bo my otrzymujemy ten zły link i jego gfy już nie odtwarza.

Tak czy inaczej, dokładnie w tym momencie naprawiamy to i w kolejnej wersji powinno wszystko działać, a jeżeli nie będzie to otworzymy link w przeglądarce :-)

**Comment by CodoDodo** [comment]
Poprawione
