### ISSUE TITLE
Złe skalowanie obrazka w tle profilu, po przejściu w tryb poziomy

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#192]
1. Wejść w profil użytkownika co ma obrazek w tle.
2. Przejść w tryb poziomy.
Rezultat:
![img_0056](https://user-images.githubusercontent.com/23238398/52587799-26c67800-2e3b-11e9-8fe2-eb914102e2c0.PNG)

Dopiero po ruszeniu, obrazek powiększa się do właściwego rozmiaru.

**Comment by CodoDodo** [comment]
Poprawione
