### ISSUE TITLE
Problemy z otwarciem linków we wpisach

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#194]
Napotykam na dziwny problem z otwarciem niektórych linków zamieszczonych we wpisach. Najlepszym przykładem są wpisy od @riley24
![img_0080](https://user-images.githubusercontent.com/23238398/52804665-0be74400-3085-11e9-8241-7b39f79b368c.PNG)

Próby kliknięcia w "tutaj" kończą się fiaskiem. Próbowałem w innych jej wpisach, to samo. Co ciekawe, po obróceniu w tryb poziomy, link działa. Testowane na XS Max.

**Comment by CodoDodo** [comment]
Jak często ten błąd występuje?
Wygląda to na problem z przeliczaniem dokładnej pozycji dotknięcia ekranu i po prostu aplikacja myśli, że nie wybrałeś linku a coś innego.

**Comment by JonahKK** [comment]
Właśnie problem ten napotykam tylko przy jej postach, pewnie z racji, unikatowego umiejscowienia linku.

**Comment by JonahKK** [comment]
W tym komentarzu nie mogę otworzyć spoileru
https://www.wykop.pl/wpis/39633609/#comment-139519667

**Comment by CodoDodo** [comment]
Poprawione
