### ISSUE TITLE
Niepoprawne tworzenie odnośnika do taga

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#196]
We wpisach, niepoprawnie tworzony jest tag, linkiem staje się całe słowo, mimo że występują w nim znaki specjalne:
![img_0120](https://user-images.githubusercontent.com/23238398/52901805-55ac6780-3208-11e9-92b5-cb04dd5e08d7.jpg)
Gdy otworzy się ten wpis przez przeglądarkę to odnośnikiem jest część do '.
Przez to nie można przejść do tagu, bo taki z apostrofem nie istnieje.

**Comment by CodoDodo** [comment]
Poprawione
