### ISSUE TITLE
Zmiany UI (Mało intuicyjne korzystanie z menu Akcje)

### ISSUE THREAD

**Issue by dobrzecisiewydaje** [CodoDodo/Zakop#20]
Z mojego punktu widzenia jest to mało wygodne, najlepiej byłoby przerzucić to do trzech kropek na belke. Albo przynajmniej wyciągnąć stamtąd najczęściej używane opcje czyli plusowanie (i minusowanie na wykopalisku).

Poza tym co z telefonami, które nie wspierają 3D Touch (wszystkie poniżej iPhone 6S)?

**Comment by CodoDodo** [comment]
Obecnie okienko akcji działa na długim przytrzymaniu, więc będzie to działało na każdym urządzeniu. 

Problem z akcjami jest taki, że są one skierowane do konkretnego użytkownika, więc muszą być gdzieś w pobliżu jego postu czy komentarza. Nie chcemy zaśmiecać widoku komentarza dla czytelności więc większość opcji jest ukryta, ale możemy pomyśleć nad przyciskami pod postem lub w rogu posta, tak jak tutaj w Apollo te trzy kropeczki https://apolloapp.io/assets/images/iphone-3.png

Takie coś byłoby lepsze? Pytanie tylko, która opcja powinna być tą domyślną, bo możemy też zrobić przełącznik w ustawieniach, albo dodać opcję do operowania gestami (długie przytrzymania lub przesunięcia w bok czy coś)

**Comment by CodoDodo** [comment]
Dodaliśmy w tym momencie Pull To Refresh w kilku miejscach :) 
To akurat nie przeszkadza nigdzie a tylko pomaga, więc dodaliśmy od razu.

**Comment by Ciema** [comment]
Jeszcze taka jedna propozycja. Przydaloby sie, wedlug mnie, zaznaczac jakos wpis/komentarz, ktory zaplusowalismy. Np paskiem (jak w oficjalnej apce) lub podswietleniem ilosci plusow (jak na www). Chyba, ze ktos ma jakis inny, oryginalny pomysl na to?

**Comment by CodoDodo** [comment]
Poprawione, a poszczególne opcje dodane :-)
