### ISSUE TITLE
Odtwarzanie filmów YT w natywnym playerze nie działa

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#200]
Jak wyżej. Filmy z YT są na moment, dosłownie sekundę załadowane w natywnym palyerze a następnie otwierają się w aplikacji YT. Wcześniej chyba odtwarzały się w natywnym.

**Comment by CodoDodo** [comment]
W przypadku gdy youtube zwróci, że film nie może zostać odtworzony, domyślnie otwiera się przeglądarka aby móc zobaczyć komunikat. 

Czy dzieje się to przy każdym filmiku? Czy możesz pokazać nam przykład?

**Comment by RichForever** [comment]
@CodoDodo wydaje się, że problem ustał sam z siebie. Na kilka przetestowanych filmów każdy otwiera się w natywnym playerze. Jeżeli błąd się powtórzy dam znać.
