### ISSUE TITLE
Krótkie tagi w wyszukiwarce

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#202]
1. Nie da się wejść przez wyszukiwarkę w tagi, które mają mniej niż 3 znaki. 
2. Wpisanie spacji w wyszukiwarce powoduje wyrzucenie błędu jn. 

![img_2691](https://user-images.githubusercontent.com/44524082/53250489-cba64800-36ba-11e9-92f7-b6f4414a8a8d.png)

**Comment by CodoDodo** [comment]
Błąd poprawiony
