### ISSUE TITLE
Gdy mamy włączony tryb nocny to automatyczna zmiana nie działa

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#206]
Tak jak w tytule:
https://gfycat.com/UnluckyHappygoluckyGrayfox

**Comment by CodoDodo** [comment]
Poprawiliśmy wyświetlanie i włączanie trybu nocnego.
Co do samego działania to tryb nocny włączy się wtedy gdy jeden z warunków do jego włączenia zostanie spełniony - więc wystarczy że jasność wyświetlacza będzie poniżej wybranej granicy lub sam tryb zostanie ręcznie włączony.
