### ISSUE TITLE
3D Touch nie działa podczas PiP

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#208]
Gdy mamy włączony PiP to nie działa 3D Touch na mediach (obrazki, gify, filmiki).

**Comment by CodoDodo** [comment]
iOS sprawdza tylko najwyższą "warstwę" okienek w iOS i w przypadku gdy mamy małe okienko odtwarzania, to 3D touch będzie działał tylko tam. Nie jest to błąd z naszej strony a cecha iOS.

**Comment by JonahKK** [comment]
Dobrze wiedzieć! Jak rozumiem nie można przesunąć to małe okienko w niższą warstwę.

**Comment by CodoDodo** [comment]
Niższą warstwą jest np. Mikroblog więc samo okienko by musiało zniknąć. Sprawdzimy czy da się coś z tym zrobić ale raczej jest to niemożliwe. 

Inną sprawą jest np. otwieranie kilku filmów na raz, raczej wydaje się to nielogiczne, bo co wtedy musiałoby się dziać?

**Comment by JonahKK** [comment]
Nie myśle nawet o filmach, a o obrazkach.  Do tego wykorzystuje 3D Touch głównie.
