### ISSUE TITLE
Odnośniki powiadomień

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#210]
Odnośniki powiadomień przenoszą do nie tych komentarzy co trzeba. 
https://imgur.com/a/smTV0VE

**Comment by CodoDodo** [comment]
Wydaje mi się, że tutaj wszystko jest tak jak powinno. Komentarz autora jest na samym dole, nie ma miejsca by go przesunąć wyżej (tak jak robimy to zwykle) ale widać go na ekranie tak czy inaczej.
Ale zgodzę się, że faktycznie trudno zauważyć co się dzieje. W następnej aktualizacji pojawi się efekt podświetlenia komentarza aby łatwiej było go znaleźć :-)
