### ISSUE TITLE
Crash aplikacji po usunięciu komentarza

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#212]
Po usunięciu komentarza i odświeżeniu apka crashuje

https://gfycat.com/GrimBewitchedAtlanticbluetang

Dotyczy wersji beta

**Comment by CodoDodo** [comment]
Poprawione

**Comment by RichForever** [comment]
Problem nadal występuje. Najnowsza beta 1.2, iPhone X, iOS 12.1.4
