### ISSUE TITLE
Kliknięcie w lewo od wyślij w prywatnych wiadomościach usuwa wiadomość

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#214]
1. Napisz coś
2. Dotknij trochę na lewo od wyślij.
Treść wiadomości zostaje usunięta.
https://gfycat.com/TameIcyAmericanpainthorse

**Comment by CodoDodo** [comment]
W trybie dziennym widać tam małą ikonkę kasowania, w nonym widocznie się nie zmienia.
Poprawimy w następnej aktualizacji!
