### ISSUE TITLE
Powiadomienie o nowej wersji aplikacji

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#217]
Mimo tego, że jest mam nową wersję pokazuje się komunikat z informacja o braku aktualnej wersji.

**Comment by CodoDodo** [comment]
Za szybko pobierasz nowe wersje haha, nie zdązyliśmy jeszcze wszystkiego zaktualizować ;-)
Sprawdź teraz czy wszystko jest ok. Może być wymagane podwójne włączenie aplikacji

**Comment by RichForever** [comment]
@CodoDodo wyglada na to, ze jest już ok ;)
