### ISSUE TITLE
Brak możliwości wybrania więcej osób w odpowiedzi.

### ISSUE THREAD

**Issue by Venntr** [CodoDodo/Zakop#22]
Odpowiadając na komentarze można wybrać "Odpowiedz" na jednym komentarzu. Otwiera się nowe okno z nazwą autora komentarza, ale by dodać więcej odbiorców trzeba ich wpisać ręcznie.

**Comment by CodoDodo** [comment]
Dodano wymieniony wcześniej edytor w wersji 7.
