### ISSUE TITLE
Niechciane otwieranie tagów

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#221]
Odnośniki we wpisach uaktywniają spory obszar, przez co nawet tapnięcie na pustą przestrzeń powoduje przejście dalej. Przykładowo - tapnięcie w zaznaczona czerwoną przestrzeń powoduje przeście do tagu 'szkoła'
 ![embed](https://user-images.githubusercontent.com/44524082/55310018-be217200-545f-11e9-87f9-c788275781fb.png)

**Comment by CodoDodo** [comment]
Poprawione
