### ISSUE TITLE
Menu dziwnie wygląda

### ISSUE THREAD

**Issue by sorhu** [CodoDodo/Zakop#232]
Wysokość dolnego paska zależy od tego, czy aplikacja została otwarta z orientacji pionowej czy poziomej.

**Comment by RichForever** [comment]
@sorhu przydalby się jakiś filmik/screen ukazujący problem. Opis jest mało jasny

**Comment by sorhu** [comment]
No tak jak w tytule. Wysokość paska "ustalana" jest podczas uruchomienia aplikacji i zależy od orientacji telefonu. Jedyny sposób na zmianę wysokości paska to restart apki.

1. Aplikacja uruchomiona podczas gdy telefon był w pozycji pionowej.
![IMG_3957](https://user-images.githubusercontent.com/49325622/55907844-20a10d80-5bd8-11e9-9475-72e56604d4c0.PNG)
![IMG_3958](https://user-images.githubusercontent.com/49325622/55907856-2565c180-5bd8-11e9-8094-431af446e41a.PNG)

1. Aplikacja uruchomiona podczas gdy telefon był w pozycji pionowej.
![IMG_3959](https://user-images.githubusercontent.com/49325622/55907868-2eef2980-5bd8-11e9-820a-affcbe8a5efd.PNG)
![IMG_3960](https://user-images.githubusercontent.com/49325622/55907871-31ea1a00-5bd8-11e9-9f37-4f26b70e6700.PNG)

**Comment by CodoDodo** [comment]
Poprawione
