### ISSUE TITLE
Nie działają linki do komentarzy po naciśnięciu „Otwórz w przeglądarce”

### ISSUE THREAD

**Issue by Macsch15** [CodoDodo/Zakop#234]
Generowany link przy próbie otwarcia linku („Otwórz w przeglądarce”) do konkretnego komentarza: 

`https://www.wykop.pl/wpis/64668605/`

Zrzut ekranu: 
https://storage.macsch15.pl/images/jTiOU4Xml6hHboaXhmMG6a3K9ugFhC.jpeg

**Comment by CodoDodo** [comment]
Poprawione
