### ISSUE TITLE
Zwijanie wątków powinno też zwijać po dotknięciu komentarza w wątku

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#235]
Tak działa na Reddit. Gdy wątek który czytamy jednak nam się niepodoba, dotknięcie któregoś komentarza  z niego powinno zwijać cały wątek.

**Comment by CodoDodo** [comment]
Dodaliśmy opcję w menu kontekstowym oraz po przesunięciu w prawo do zwijania wątku. 
Chowanie przez klikanie może być nieco nieintuicyjne gdy zwijamy główny wątek
