### ISSUE TITLE
Można zablokować samego siebie

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#237]
Korzystając z aplikacyjnej blokady użytkownika, można zablokować samego siebie. W przypadku wykopowej nie jest to możliwe.

**Comment by CodoDodo** [comment]
@JonahKK Czy jesteś zalogowany w aplikacji?
W którym miejscu znalazłeś przycisk do zablokowania samego siebie?

**Comment by JonahKK** [comment]
Po wejściu w Menu > Twój profil i tam można otworzyć menu gdzie  jest opcja do zablokowania się (Zablokuj tylko w aplikacji)

**Comment by CodoDodo** [comment]
Poprawione
