### ISSUE TITLE
Zbyt długie nazwy widoków

### ISSUE THREAD

**Issue by sorhu** [CodoDodo/Zakop#241]
No ja wiem, że jak się ma SE, to się nie narzeka, no ale nie wygląda to dobrze. 
Może zrobić Tylko użytkownicy / Tylko tagi.
Albo Obserwowani użytkownicy / Obserwowane tagi. 

![C52FA164-3495-46C0-8E26-BDCA236D045B](https://user-images.githubusercontent.com/49325622/56989022-b9042f80-6b91-11e9-9378-0254cebf6820.jpeg)

**Comment by CodoDodo** [comment]
Poprawione
