### ISSUE TITLE
Wejście w listę obserwujących profil Wykop zwraca błąd

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#243]
Tak jak w tytule, zapewne spowodowane jest to ilością obserwujących.

**Comment by CodoDodo** [comment]
Niestety, ale podczas wykonywania tej czynności API Wykopu zwraca błąd i nie możemy z tym nic zrobić. Wygląda na to, że ładowane są wszystkie dane za jednym razem (ponad 740 000 wyników!) albo przynajmniej częściowo (ale nadal w dużej liczbie) i po prostu sam Wykop nie wytrzymuje takiego obiążenia.
