### ISSUE TITLE
Naprawmy shruga

### ISSUE THREAD

**Issue by sorhu** [CodoDodo/Zakop#245]
Shrug wpisany tak ¯\\\_(ツ)\_/¯ wyświetla się tak ¯\_(ツ)_/¯.
Trzeba wpisać tak ¯\\\\\\\_(ツ)\\\_/¯, żeby wyświetlił się tak ¯\\\_(ツ)\_/¯.

Opcja wyboru emoty powinna to uwzględniać. ¯\\\_(ツ)\_/¯

**Comment by CodoDodo** [comment]
Z tego co widzę Wykop posiada problem z wyświetlaniem Shruga. Wpisany normalnie np. w prywatnej wiadomości ten wyświetli się w taki sam niepoprawny sposób. 

Naprawiliśmy to ale sam Wykop powinien się za to wziąć ;-)
