### ISSUE TITLE
Odświeżanie powiadomień nie działa poprzez pull&refresh

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#252]
Jak w tytule. Po otrzymaniu powiadomienia, będąc na ich liście nie są one odświeżane poprzez gest przeciągnięcia. Dopiero kliknięcie w przycisk odśwież faktycznie odświeża listę. Szczegóły na filmiku.

https://gfycat.com/impracticalmeekkentrosaurus

**Comment by CodoDodo** [comment]
Poprawione
