### ISSUE TITLE
Zakładka „Wykop” cały czas się wyświetla

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#268]
Wysyłałem to też przez Apkę, ale chyba wolicie tutaj:
Miałem zawsze ukryte wszystkie zakładki, po aktualizacji do bety, zakładka „Wykop” jest dodana na stałe. 
![8C81AF35-925C-492C-9598-BE8C17E54EEC](https://user-images.githubusercontent.com/23238398/85451556-51315500-b59a-11ea-8f04-86522efd7b12.png)

**Comment by CodoDodo** [comment]
Czy korzystałeś wcześniej z trybu "full screen"? 
W kolejnej (obecnej) wersji postanowiliśmy pozbyć się opcji wyłączenia toolbara aby (ostatecznie w niedalekiej przyszłości) wprowadzić pełny tryb tabletowy gdzie taki toolbar będzie wymagany.

**Comment by JonahKK** [comment]
Jeżeli przez fullscreen macie na myśli zupełny brak tego dolnego toolbara, to tak. Dodatkowo, jak włączę opcję „strona główna” to mam dwie
![DCEFF9AA-D997-4DB6-9AC8-8F60A8582E99](https://user-images.githubusercontent.com/23238398/85460863-fac91400-b5a3-11ea-965b-4ecdf43386ec.png)

**Comment by CodoDodo** [comment]
@JonahKK A to bubel, z tym podwójnym wykopem :D Poprawimy. Co do toolbara - nie planujemy w obecnym momencie wracać do poprzedniego rozwiązania.

**Comment by CodoDodo** [comment]
Błąd został poprawiony.
Gdyby jednak zdarzyła się podobna sytuacja w przyszłości to prosimy o kolejne zgłoszenie
