### ISSUE TITLE
„Mój Wykop”, „Prywatne wiadomości” i „Ulubione” opcje nie działają w Menu

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#278]
Kliknięcie tych opcji nie powoduje otwarcia odpowiednich widoków.

**Comment by CodoDodo** [comment]
Zgłaszamy błąd w opisie! :)

**Comment by JonahKK** [comment]
Szybcy jesteście ;)

**Comment by CodoDodo** [comment]
Zgłoszone zakładki już działają :)
