### ISSUE TITLE
Pasek nad nawigacją

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#279]
Nad nawigacją, w trybie ciemnym, jest pasek który przysłania widok. 
![9EDAB8BD-FCCB-4042-A8C9-EB8E2746D5EA](https://user-images.githubusercontent.com/23238398/85463215-ad01db00-b5a6-11ea-816a-108d50559498.jpeg)

**Comment by CodoDodo** [comment]
Poprawione
