### ISSUE TITLE
Brak możliwości dodania „Wiadomości” do nawigacji

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#282]
Włączenie opcji nie skutkuje dodaniem tej opcji do nawigacji. 
![1AFD2414-23AC-47CD-8D03-38F7136C66EC](https://user-images.githubusercontent.com/23238398/85464456-f141ab00-b5a7-11ea-90d6-e42e985777ec.png)

**Comment by CodoDodo** [comment]
Dodano w wersji 64 beta
