### ISSUE TITLE
Możliwość odświeżenia ustawień

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#283]
Można odświeżyć Ustawienie, co jest niepotrzebne. Odświeżenie trwa w nieskończoność. 
![AABA8E0D-5007-4F8E-8110-7A06AB660D58](https://user-images.githubusercontent.com/23238398/85519590-0519fb00-b602-11ea-95ed-1d034d72b8d6.png)

**Comment by CodoDodo** [comment]
Poprawione!
