### ISSUE TITLE
Ustawienia (zakładki) - suwaki pokazują błędne informacje

### ISSUE THREAD

**Issue by qweluke** [CodoDodo/Zakop#285]
Suwaki pokazują większość opcji na off mimo że faktycznie są włączone.
Dopier włączenie, wyłączenie i ponowne włączenie pokazuje faktyczny stan.
Wygląda na to, że problem jest tylko podczas pierwszego uruchomienia

**Comment by CodoDodo** [comment]
Poprawione :)
