### ISSUE TITLE
Kliknięcie w nazwę użytkownika otwiera stronę z błędnym nickiem

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#286]
Klikając w komentarzu na nick, zostajemy przekierowani na stronę z błędem. Podczas przekierowania jest dodane jeszcze jeden znak „@„, przez co zwracany jest błąd że nie ma takiego użytkownika. 
![FB2C0FAC-520E-4AD6-977B-7B43B00FA518](https://user-images.githubusercontent.com/23238398/85865181-c9c82980-b7c5-11ea-97e8-de49409da357.png)

**Comment by CodoDodo** [comment]
Poprawione :)
