### ISSUE TITLE
Ankieta pojawia się również w komentarzach

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#287]
Gdy wpis ma ankietę to niektóre komentarze mają ją również
![D3A37D72-4073-4A30-AAAB-2E156AF799A2](https://user-images.githubusercontent.com/23238398/86212398-3fdae080-bb78-11ea-8066-c1396ec8bcb3.png)
![5B8241A3-6DE6-46E5-9485-7F8823B97BCD](https://user-images.githubusercontent.com/23238398/86212408-449f9480-bb78-11ea-8b2b-f561dc5819e6.png)

**Comment by CodoDodo** [comment]
Poprawione
