### ISSUE TITLE
Mój wykop, dublowanie wpisów.

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#29]
Powielenia pojawiają się 
1) po przewinięciu w dół listy z wpisami i wczytaniu kolejnych
2) wyjściu i ponownym wejściu do okna Mój wykop z menu

Plus od czasu do czasu apka wyrzuca przy geście cofania do poprzedniego okna

https://imgur.com/a/SiNZq33

**Comment by Cideu** [comment]
+ Od czasu do czasu aplikacja wyrzuca przy geście cofania do poprzedniego okna.

**Comment by CodoDodo** [comment]
Dublowanie zostało poprawione w wersji 5. 
Crash mamy nadzieję, że też 👍
