### ISSUE TITLE
Zwijanie okna odpowiedzi - nie działa zwijanie gestem 

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#293]
We wcześniejszych wersjach aby zminimalizować okienko odpowiedzi wystarczyło kliknąć w górną krawędź. Teraz to nie działa i trzeba przeciągnąć okno z góry do dołu

**Comment by CodoDodo** [comment]
Postanowiliśmy całkowicie usunąć opcje minimalizowania okienka odpowiedzi. 
W wersji bodajże 62 ta opcja została usunięta.

W przyszłości będziemy chcieli zastąpić ją małym elementem z opcją szybciej odpowiedzi od razu w wątkul
