### ISSUE TITLE
Meatballs menu w tagu nic nie robi

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#297]
Próba otwarcia menu niczym nie skutkuje. 
![75F6815C-33C6-459B-B9BD-4083F418EED8](https://user-images.githubusercontent.com/23238398/109928400-b579ec00-7cc5-11eb-8a18-2993d8e6351b.jpeg)

**Comment by CodoDodo** [comment]
Usunęliśmy meatballsy :) Dzięki!
