### ISSUE TITLE
Nowy wygląd ankiet jest nieczytelny na ciemnym motywie

### ISSUE THREAD

**Issue by JonahKK** [CodoDodo/Zakop#300]
Jak, w tytule, ledwo widać rozkład głosów
![99A4B014-2DA3-425D-B3D0-3BA94F05BBAE](https://user-images.githubusercontent.com/23238398/111608755-de2bd680-87d9-11eb-8e55-d55e1f1831dd.jpeg)

**Comment by CodoDodo** [comment]
Poprawione w wersji 61 Bety
