### ISSUE TITLE
[UI] Błąd animacji w widoku

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#305]
W ustawieniach „Wygląd” strona podczas scrollu do góry odskakuje. Powoduje to np niewyrównanie labelka. Poniżej filmik. Test na iPhone 12, najwnowszy iOS i wersja z TestFlight

https://streamable.com/h6w3sf

**Comment by CodoDodo** [comment]
Nie jest to błąd a przewidziane zachowanie, po prostu na tej liście nie ma wystarczajaco miejsca aby nagłówek w pełni się zawinął :P
