### ISSUE TITLE
Zapamiętywanie ustawień Mikrobloga

### ISSUE THREAD

**Issue by Venntr** [CodoDodo/Zakop#31]
Po wejściu na Mikroblog dobrze by było by aplikacja wczytywała dane na podstawie ustawień, które ostatnio włączyliśmy. Przykładowo "Gorące - 12h". Aktualnie za każdym wejściem wczytują się domyślnie nowe.

**Comment by CodoDodo** [comment]
Świetny pomysł! Chcieliśmy dodać do tego opcję w ustawieniach, ale ten pomysł jest nawet lepszy.
Dodamy w kolejnej wersji

**Comment by CodoDodo** [comment]
Dodane w wersji 5, aktualizacja wkrótce :)
