### ISSUE TITLE
Oznaczenie wpisu jako ulubionego 

### ISSUE THREAD

**Issue by mtsz-pl** [CodoDodo/Zakop#312]
Fajnie byłoby, gdyby wpis na Mirko oznaczony jako ulubiony, miał jakąś ikonkę małego serduszka w nagłówku, ewentualnie w okolicy liczby plusów.Z dokumentacji wynika, że wpis ma pole `user_favorite`, które można do tego wykorzystać.

**Comment by CodoDodo** [comment]
Fajny pomysł, już nawet mam pomysł jak to pokazać :)

**Comment by CodoDodo** [comment]
Dodano, funkcja będzie dostępna w kolejnym update 

![image](https://user-images.githubusercontent.com/44480523/122830764-16ffae00-d2e9-11eb-9945-9d8dc3fb1c9f.png)
