### ISSUE TITLE
Zakładka Mój Wykop: powiadomienia nie znikają 

### ISSUE THREAD

**Issue by dobrzecisiewydaje** [CodoDodo/Zakop#320]
Po wejściu w zakładkę Mój Wykop i przejrzeniu obserwowanych wpisów, czerwona naklejka z ilością powiadomień nie znika. Dochodzą do niej kolejne powiadomienia i ich ilosc ciagle się sumuje.

**Comment by CodoDodo** [comment]
Poprawione w kolejnym release :)
