### ISSUE TITLE
Plusowanie wysypuje apke

### ISSUE THREAD

**Issue by suqmadiq2ama** [CodoDodo/Zakop#34]
Reinstal trochę pomógł że da sie otworzyć

https://youtu.be/gV5QhnomDtM

**Comment by dobrzecisiewydaje** [comment]
Korzystasz już z wersji na TestFlight? Bo w tej becie problem juz został rozwiązany - issue #16 w zakładce Closed.

**Comment by suqmadiq2ama** [comment]
Tak

**Comment by CodoDodo** [comment]
Chyba można zamknąć. W przypadku podobnego błędu w przyszłości prosimy o otwarcie nowego wątku.
