### ISSUE TITLE
Nie działają gify

### ISSUE THREAD

**Issue by michalw1987** [CodoDodo/Zakop#37]
Bezpośrednio w aplikacji często nie działają gify https://youtu.be/NWK1w0-IMig

**Comment by CodoDodo** [comment]
Hmmm, da się wczytywać gify i jest to obsłużone. Być może ten jeden jest uszkodzony?
Sprawdzimy!

**Comment by michalw1987** [comment]
Problem występuje losowo. Niektóre działają a inne nie.

**Comment by Cideu** [comment]
@CodoDodo Brakuje trochę animacji wczytywania do gifu. Nie wiadomo czy się ładuje, czy nie

**Comment by CodoDodo** [comment]
@Cideu Zgadzam się, trzeba dodać :)

**Comment by CodoDodo** [comment]
Poprawione, zmiana będzie widoczna w wersji 8
