### ISSUE TITLE
Głosowanie w ankiecie

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#38]
Brak możliwości głosowania w ankietach

**Comment by CodoDodo** [comment]
Nie jesteśmy pewien czy jest to dostępne jeszcze w API, damy znać i dodamy odpowiednią notatkę przy ankietach

**Comment by CodoDodo** [comment]
Niestety Wykop nadal nie udostępnia tej opcji, póki co zamykamy temat bo nie ma szansy na jego rozwinięcie :-( 👎
