### ISSUE TITLE
"Pokaż spoiler" jest mało czytelny w trybie nocnym.

### ISSUE THREAD

**Issue by michalw1987** [CodoDodo/Zakop#41]
![img_1003](https://user-images.githubusercontent.com/44526058/47738024-84f79280-dc72-11e8-9865-846f82a8b606.PNG)
![img_1004](https://user-images.githubusercontent.com/44526058/47738061-99d42600-dc72-11e8-9981-f2ae797947b2.PNG)

**Comment by CodoDodo** [comment]
Duplikat https://github.com/CodoDodo/Zakop/issues/5.
Pracujemy nad tym
