### ISSUE TITLE
Mniej wpisów w gorących niż na oficjalnej apce.

### ISSUE THREAD

**Issue by Venntr** [CodoDodo/Zakop#42]
Czy to ograniczenie API czy jakiś bug, że aplikacja Zakop wczytuje mniej wpisów w gorących niż oficjalna aplikacja? Przykład na 6h gorących, strzałka wskazuje, że jest jeszcze dużo wpisów dalej, gdzie aplikacja Zakop już doszła do końca.

[
![2427280c-5d64-4d9c-8777-b327e99515da](https://user-images.githubusercontent.com/16389517/47806142-509ad980-dd39-11e8-896b-75594627b4d9.png)
![dd230ec7-a0e5-40c1-bb0b-13b2e1e145a2](https://user-images.githubusercontent.com/16389517/47806143-51337000-dd39-11e8-9fa2-36a840c149f0.jpeg)

](url)

**Comment by Ciema** [comment]
Potwierdzam. U mnie wyswietla sie ok 60-70 wpisow w goracych z 6h i ok 90 wpisow z goracych 24h.

Gdzie na stronce jest 10 stron po 20 wpisow.

**Comment by Ciema** [comment]
Sprawdzilem wlasnie na oficjalnej apce. Wyswietla sie ok 200 wpisow wiec podobnie jak na stronie www. 

Wychodzi na to, ze grubo ponad polowa wpisow nie wyswietla sie w Zakopie.

**Comment by CodoDodo** [comment]
@Ciema @Venntr To niestety ale jedna z cech Wykopowego API. Wpisy są ładowane tak jak na stronie, a jak pewnie wiecie, czasem zdarza się że jedna podstrona na Wykopie jest całkowicie pusta (widać to dobrze np. podczas meczu, kiedy cały mikroblog jest zasypany tagiem #mecz). Kiedy otrzymujemy brak danych, wtedy zatrzymujemy wczytywanie.

Zmieniliśmy to i obecnie wczytujemy dodatkowo jeszcze dwie kolejne strony i dopiero jeżeli w tych trzech przypadkach brak jest danych, to zatrzymujemy wczytywanie.

**Comment by Ciema** [comment]
@CodoDodo dzieki, zdam relacje po update'cie

**Comment by Ciema** [comment]
No wiec teraz widze:
82 wpisy w goracych z 6h 
83 wpisy w goracych z 24h

To wciaz mniej niz polowa wpisow.

Mozecie jeszcze sprawdzic u siebie? 
@CodoDodo @Venntr @Cideu @michalw1987 @suqmadiq2ama @dobrzecisiewydaje

**Comment by CodoDodo** [comment]
@Ciema Jesteś pewien, że sprawdzasz całość na najnowszej wersji aplikacji i na tym samym zalogowanym kocnie? 

Sprawdziliśmy w tym momencie i mamy tyle samo (albo nawet więcej) wpisów w naszej apce - w przypadku 24h widzimy też te nowsze wpisy i jakimś cudem one nie są widoczne w oficjalnej.
Mówimy tutaj tylko o aplikacjach mobilnych.

**Comment by CodoDodo** [comment]
@Ciema Jak po czasie oceniasz teraz zachowanie aplikacji w tym aspekcie?

**Comment by michalw1987** [comment]
Jest dobrze. U mnie nie ma z tym problemu

W dniu śr., 12.12.2018 o 19:37 Codo Dodo <notifications@github.com>
napisał(a):
