### ISSUE TITLE
Ucinanie komentarzy we wpisach

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#44]
https://imgur.com/a/T7c2jdq

**Comment by CodoDodo** [comment]
Wkrótce wydamy nową aktualizację, dasz nam wtedy znać czy problem się powtarza?

**Comment by Cideu** [comment]
@CodoDodo jak narazie ucinania nie widać

**Comment by CodoDodo** [comment]
To zamykamy, w razie kolejnych problemów prosimy o nowy temat
