### ISSUE TITLE
Nie działa opcja ukryj #nsfw 

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#45]
- ukrywane jest tylko część wpisów tagowanych #nsfw 
- ukryte wpisy są oznaczone jako +18, a nie NSFW (to dwie różne opcje na wykopie)

https://imgur.com/a/WQCsq04

**Comment by CodoDodo** [comment]
Tutaj chodziło nam o ukrywanie podglądu obrazków oznaczonych jako +18. Ukrywanie całych wpisów jest jeszcze do obsłużenia z poziomu API
