### ISSUE TITLE
Zawijanie długich wpisów

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#47]
Długie wpisy ukrywają ciąg dalszy nie tylko w widoku listy ale też w oknie z pojedynczym wpisem.
Tam, mogłyby wyświetlać się odrazu w całości.

https://imgur.com/a/Szpro6o

**Comment by Ciema** [comment]
@Cideu ale jest przycisk "Czytaj dalej". Moim zdaniem jest OK.
Czytasz caly wpis po rozwinieciu w widoku listy a pozniej przechodzac do wpisu czytasz sobie komenatrze bez potrzeby rozwijania calego wpisu (ktory moze czasem zajmowac duzo miejsca).

**Comment by CodoDodo** [comment]
@Ciema Tutaj chodzi o rozwinięcie wpisu po przejściu do jego komentarzy.
@Cideu Sam nie wiem co o tym sądzić, z jednej strony masz rację, można wpis pokazać w całości od razu. Z drugiej jednak jeżeli czytamy już wcześniej rozwinięty wpis, to przewijanie go drugi raz jest bez sensu. Co o tym sądzisz?

**Comment by Ciema** [comment]
@CodoDodo moim zdaniem powinno zostac, jak jest obecnie. Dla mnie to bardzo wygodne.

**Comment by Cideu** [comment]
@CodoDodo To może zwiększyć tylko liczbę znaków, po których w widoku pojedynczego wpisu byłby on zawijany.

**Comment by CodoDodo** [comment]
@Cideu Poprawiliśmy w wersji 7 zwijanie - dodaliśmy więcej znaków i ulepszyliśmy wczytywanie. Czy teraz jest nieco lepiej?

**Comment by Ciema** [comment]
@CodoDodo jak dla mnie to jest zajebiscie.

**Comment by CodoDodo** [comment]
No to super!
W razie chęci kolejnych poprawek, prosimy o otwarcie nowego wątku. 
Póki co zamykamy temat!
