### ISSUE TITLE
Powrót do menu

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#48]
Brak możliwości szybkiego powrotu do menu. Po wejściu w kilka odnośników z rzędu, jedyną opcją jest kilkukrotne klikanie powrót. 

Może przydałoby się menu dolne, z takimi odnośnikami -  jak w Apollo.

**Comment by CodoDodo** [comment]
Ale w Apollo jest taka sama sytuacja, co dokładnie masz na myśli?

**Comment by Ciema** [comment]
@CodoDodo ale w Apollo zawsze mozesz tapnac na "Posts" na dolnym menu i wracasz do glownej listy wpisow.

**Comment by CodoDodo** [comment]
@Ciema Słuszna uwaga, dodaliśmy taką funkcję w jednej z poprzednich wersji więc odznaczamy jako zrobione :-)
