### ISSUE TITLE
Lenny crash

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#49]
Appka wywala każdorazowo po tąpnięciu ikony emotek w oknie tworzenia nowego wpisu\komentarza

ᕙ(⇀‸↼‶)ᕗ

**Comment by Ciema** [comment]
@CodoDodo @Cideu potwierdzam. u mnie to samo.

**Comment by CodoDodo** [comment]
Ale babol! Poprawimy

**Comment by CodoDodo** [comment]
Poprawione!
