### ISSUE TITLE
Spiolery w trybie nocnym maja czarna czcionke.

### ISSUE THREAD

**Issue by Ciema** [CodoDodo/Zakop#5]
![img_0682](https://user-images.githubusercontent.com/44483439/47535049-a0008600-d8b1-11e8-897e-6461b62e024a.png)

**Comment by CodoDodo** [comment]
iOS słabo sobie jeszcze radzi z trybem nocnym, wszystkie okienka są takie w ciemnym trybie. 
Poprawimy to tak szybko jak możemy

**Comment by CodoDodo** [comment]
Done, poprawka będzie dostępna w następnej aktualizacji
