### ISSUE TITLE
Animacja ładowania w trybie OLED

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#50]
Niewidoczny spinner ładowania w pull to refresh w trybie oled.

**Comment by Ciema** [comment]
@CodoDodo potwierdzam, u mnie to samo. Mozna by zmienic jego kolor w trybie OLED na szary.

**Comment by CodoDodo** [comment]
Poprawimy!

**Comment by Cideu** [comment]
@CodoDodo samo odświeżanie też czasami nie działa - po zakończeniu animacji nie pojawiają się nowe wpisy
