### ISSUE TITLE
Ustawianie trybu OLED

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#51]
1) W opcjach appki włączenie 'trybu oled' przy wyłączonym 'używaj trybu nocnego' powoduje, że appka wyświetla się w trybie dziennym.
2) Literówka 'Użytaj trybu nocnego'

**Comment by CodoDodo** [comment]
1. To nie jest błąd, tryb OLED jest rozszerzeniem trybu nocnego a nie osobnym "bytem" :P
2. Uu, faktycznie, dzięki!

**Comment by Cideu** [comment]
It's not a bug, it's a feature ( ͡° ͜ʖ ͡°)

**Comment by CodoDodo** [comment]
Literówka poprawiona, z OLEDem wszytko jasne to zamykam
