### ISSUE TITLE
Etykieta 'nowy'

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#52]
Jestem skonfundowany co ma sygnalizować i jak działać etykieta 'nowy' przy wpisach, w oknie Mój wykop. Etykieta nie znika po odświeżeniu, po wyjściu i ponownym wejściu do okna 'mój wykop', ani po otworzeniu konkretnego wpisu.

**Comment by Ciema** [comment]
@Cideu chodzi ci o to: #6 ?

**Comment by Cideu** [comment]
@Ciema: o te etykiety https://imgur.com/a/9DdcGOM

**Comment by Ciema** [comment]
@Cideu pewnie jest to powiazane z problemami z #6

**Comment by CodoDodo** [comment]
@Cideu @Ciema Etykiety "nowy" mają się pojawiać tam, gdzie będą nowe wpisy. Problem w tym, że Wykop tego oficjalnie nie wspiera i uzupełniamy to sami. Dodaliśmy to do powiadomień oraz Mojego Wykopu, gdzie zaznaczamy tyle wpisów, ile jest powiadomień z tagów. Jak pewnie zauważyliście, działa to tak sobie bo niektóre tagi nie są w ogóle liczone do licznika powiadomień z tagów i czasami jest to niedokładne.
W obecnej wersji dodaliśmy to do testów, możliwe że w przyszłości to zniknie.

**Comment by CodoDodo** [comment]
@Cideu dobra uwaga!
