### ISSUE TITLE
Powiadomienia do znaleziska

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#53]
Nie działają odnośniki z panelu powiadomienia jeśli ktoś woła w komentarzu pod znaleziskiem. 
Powiadomienie z wołania na mirko odsyła normalnie do konkretnego komentarza.

**Comment by CodoDodo** [comment]
Nad powiadomieniami jeszcze pracujemy.
Push nie wiem czy będzie bo chyba tego Wykop nie wspiera. Jeżeli jest to w innych aplikacjach to będzie i u nas.

**Comment by CodoDodo** [comment]
Poprawione w wersji 8
