### ISSUE TITLE
Dostęp do elementów wykopu, układ menu

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#55]
Brak zakładki aktywne wpisy, oprócz ‚wszystkie’ i ‚gorące’ na mikroblogu.

Edit: @CodoDodo Właściwie to jak i #48  jest częścią większej rzeczy, która mi osobiście zaczyna doskwierać w UI — a więc dużej ilości tapnięć potrzebnych do otwarcia konkretnego interesującego nas okna. Może to tylko moje odczucie ale wydaje mi się, że potrzeba więcej bezpośredniego dostępu do kolejnych części wykopu już z poziomu menu. Coś w tym stylu — 

Strona Główna
———————————
	Najnowsze 
	Aktywne 
	Hity

Wykopalisko
———————————
	Najnowsze
	Aktywne
	Komentowane

Mikroblog
———————————
	Wszystkie wpisy
	Aktywne wpisy
	Gorące dyskusje

Szybkie linki
———————————
	(...)

Ustawienia

Do tego z dolnym menu - jak w Apollo, które mogłoby zawierać takie elementy jak:

Profil | Mój wykop	| Powiadomienia | Wyszukiwarka

**Comment by CodoDodo** [comment]
Nie lepszym pomysłem byłoby dodanie wysuwanego menu po przesunięciu z lewej, tak jak proponowały różne osoby w https://github.com/CodoDodo/Zakop/issues/20 i https://github.com/CodoDodo/Zakop/issues/10 ?

**Comment by Cideu** [comment]
@CodoDodo Coś takiego jak w oficjalnej apce wykopu? Też nie jest to zła opcja tylko hamburger menu jest takie androidowe ( ͡° ͜ʖ ͡°)  i przypadku takiej wysuwanej konstrukcji zdarzają się niechciane wywołania, bo niedaleko temu do gestu cofania. Mi osobiście bardzo przypadł do gustu układ podobny do Apollo - jest więcej miejsca na odnośniki.

**Comment by Cideu** [comment]
@CodoDodo Dokładnie coś takiego miałem na myśli. https://imgur.com/a/Yv6tUk6 Aby wyciągnąć więcej opcji "na wierzch" i było mniej tapnięć.

**Comment by CodoDodo** [comment]
@Cideu Czy teraz jest lepiej i temat można zamknąć? :)

**Comment by Cideu** [comment]
@CodoDodo O niebo lepiej! Myślę, że można zamknąć.
