### ISSUE TITLE
Oznaczenie zaplusowanego wpisu

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#57]
Brak rozróżnienia dla zaplusowanego wpisu. Przydałoby się to poprawić np zielone tło i biały tekst

**Comment by CodoDodo** [comment]
Dobry pomysł, dodamy wkrótce!

Tylko tło będzie wymagało zmiany wymiarów albo ułożenia tekstu - może mała strzałka obok punktów byłaby lepsza?

**Comment by RichForever** [comment]
@CodoDodo mysle, ze stan szary/kolorowy bedzie w tym wypadku najlepszym wyjsciem. Raz, ze nie naruszymy struktury a dwa, ze bedzie to intuicyjne.

**Comment by CodoDodo** [comment]
@RichForever Tylko na Wykopie jest już przyjęty ten zielony kolor, więc nie wiem czy nie będzie to zbytnie odejście od ich formatu

**Comment by CodoDodo** [comment]
@RichForever Dodaliśmy małą ikonkę plusa lub minusa obok punktów :) Poprawka będzie dostępna w następnej wersji

**Comment by RichForever** [comment]
Nowe oznaczenie plusowanego wpisu jest nieintuicyjne. + przy liczbie może sugerować, ze plusów jest więcej niż np. 8+ mówi mi ze jest więcej niż 8 plusów. Nadal oponowałbym za innym oznaczeniem :D
