### ISSUE TITLE
ObjectMapper failed to serialize response 

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#58]
Zdarza się, że appka wyrzuca taki błąd w każdym kolejnym otworzonym oknie (czy to wykopalisko, główna, mój wykop). Pomaga dopiero wymuszone zamknięcie. https://imgur.com/a/gRoYe9U

**Comment by CodoDodo** [comment]
Trafiłeś akurat na prace serwisowe i pewnie Wykop zwraca taką informację, nasza aplikacja po prostu jeszcze o tym nie informuje. Ale jak najbardziej do szybkiej poprawy

**Comment by CodoDodo** [comment]
Poprawione w wersji 9
