### ISSUE TITLE
Panel tworzenia wpisu

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#60]
1. Próba publikacji wpisu zawierającego wyłącznie nick mirka lub symbol formatowania tekstu, cytat i spoiler powoduje taki komunikat https://imgur.com/a/reMvPC3 Z tego co rozumiem wykop traktuje dalej te wpisy jako puste. Może wyłączenie i wyszarzenie przycisku 'Opublikuj' przy takich przypadkach by pomogło?
2. W trybie ciemnym i OLED nagłówek okna tworzenia wpisu zlewa się z tłem https://imgur.com/a/hLZF4sE
3. Przy włączeniu/wyłączeniu trybu nocnego w trakcie tworzenia wpisu panel nie zmienia koloru
https://imgur.com/a/siG1MMW
4. Nie da się anulować tworzenia wpisu kiedy jest panel jest zwinięty. Jeśli tak miało być, to z drugiej strony —  nie znikają przyciski 'Anuluj' i 'Opublikuj', a są jedynie wyszarzone.
5. Animacja zsuwania i rozsuwania panelu z nowym wpisem jest trochę nienaturalna, w porównaniu np do Mail app, gdzie palcem można przesunąć od dołu do góry, ładniej wg mnie wyglądałby też systemowy pasek niż strzałka ⋁ https://imgur.com/a/jIK1Tqb

**Comment by CodoDodo** [comment]
1. https://github.com/CodoDodo/Zakop/issues/58
2. Do poprawy faktycznie
3. Do poprawy
4. Tak miało być 👍 
5. Brakuje przeciągania, można faktycznie to dodać w wolnej chwili wraz z ikonkami

**Comment by Cideu** [comment]
@CodoDodo V jest chyba trochę za blisko home bara, czasem się zdarza że zamknę apkę zamiast rozwinąć panel

![img_2373](https://user-images.githubusercontent.com/44524082/50891143-f040ac00-13fb-11e9-9453-aa9b50e8d7c5.jpg)

**Comment by CodoDodo** [comment]
@Cideu Poprawione plus dodana została opcja do zwijania panelu przez przeciągnięcie :-)
