### ISSUE TITLE
Tryb OLED, dziwne zachowanie 

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#64]
https://streamable.com/kn0ka

**Comment by CodoDodo** [comment]
Rozgryzłeś sposób ustalania kolorów w aplikacji ;-)
Zmieniamy tylko tak naprawdę pierwsze menu (bo tam są ustawienia) oraz belki na górze, bo założyliśmy, że reszta będzie wczytywana od początku :P

**Comment by CodoDodo** [comment]
Poprawione w wersji 9
