### ISSUE TITLE
Kolory tła w trybie dziennym

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#68]
Część okien ma tła w F6F6F6 a niektóre są białe.

**Comment by CodoDodo** [comment]
O których miejscach dokładnie mowa?

**Comment by CodoDodo** [comment]
@Cideu up up, o które miejsca dokładnie chodzi?

**Comment by Cideu** [comment]
Wydawało mi się, że w oknie Mój Wykop. Ale sprawdziłem teraz ponownie i się wszędzie zgadza.

**Comment by CodoDodo** [comment]
No to zamykamy ;) 
Przy okazji dziękujemy za tak dokładne opisy, to nam bardzo pomaga! @Cideu
