### ISSUE TITLE
Brak mozliwosci otwarcia znaleziska w apce (tylko w safari).

### ISSUE THREAD

**Issue by Ciema** [CodoDodo/Zakop#7]

**Comment by CodoDodo** [comment]
@Ciema masz na myśli tutaj przejście z safari do apliakcji czy o linki wewnątrz aplikacji, które otwierają się tylko w przeglądarce? Dobry pomysł z przechodzeniem wewnątrz programu.

**Comment by Venntr** [comment]
Link wewnątrz aplikacji byłby wygodniejszy niż wymuszanie otwierania Safari. Podobnie jest z linkami we wpisach na Mikroblogu.

**Comment by Ciema** [comment]
@CodoDodo otwieranie linkow/znalezisk wewnatrz aplikacji. otworzenie w safari powinno byc wedlug mnie jako opcja a nie jako glowne rozwiazanie.

**Comment by CodoDodo** [comment]
@Ciema @Venntr Racja. Dodamy w jednej z kolejnych akutalizacji
