### ISSUE TITLE
Zakrywanie menu dolnego

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#72]
Na początku zostawiam serduszko, bo menu dolne dodało dużo dobrego szybkości nawigowania ❤️

Panel tworzenia wpisu zakrywa menu i uniemożliwia nawigację https://imgur.com/a/h2RIYP4

**Comment by CodoDodo** [comment]
No to ładnie wymyśliliśmy :) 
Ale nowe błędy też trzeba dodać w aktualizacji (✌ ﾟ ∀ ﾟ)☞

**Comment by CodoDodo** [comment]
Poprawione
