### ISSUE TITLE
Migająca ikona apki

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#73]
https://streamable.com/jbxkp

**Comment by CodoDodo** [comment]
Dziwne, może iOS ma jakąś kopię ikony w pamięci i powoduje to taki efekt?
Możesz uruchomić ponownie telefon i sprawdzić czy też to się dzieje?

**Comment by Cideu** [comment]
@CodoDodo Po restarcie telefonu efekt zniknął. Gdyby wróciło to będę pisał.

**Comment by Cideu** [comment]
@CodoDodo na iPadzie przyciski nie odpowiadają, a reset nie pomaga 
https://streamable.com/djc8n

**Comment by CodoDodo** [comment]
@Cideu Błąd na iPadzie już poprawiliśmy, poprawka będzie dostępna w wersji 12
