### ISSUE TITLE
Brak możliwości zapisywania obrazków/gifów w galerii 

### ISSUE THREAD

**Issue by yoyebie** [CodoDodo/Zakop#74]
Gdy chcę zapisać obrazek/gif w galerii, muszę robić to z poziomu Safari. Przydałaby się możliwość zapisywania obrazków bezpośrednio w aplikacji, a także możliwość ich udostępniania  (nie linków do wpisów, a samych obrazków).

**Comment by Cideu** [comment]
Potwierdzam, to by było przydatne

**Comment by CodoDodo** [comment]
Dodane w poprzedniej wersji :-) Zamykam
