### ISSUE TITLE
Strona tagu

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#77]
Mam uwagi dotyczące okna tagu. 

1. Zdecydowana większość tagów na wykopie nie ma ani opisu ani grafiki. A w oknie tagu w apce znajduje się duży paceholder i miejsce na opis. Wydaje mi się, że to niepotrzebne zabieranie przestrzeni. Taka grafika i/lub opis mógłby się wyświetlać, gdyby dany tag go miał. Jak myślicie?

2. Domyślnie na stronie tagu na www wykopu wyświetla się miks znalezisk i wpisów. W apce jest odwrotnie trzeba najpierw wybrać filtr (znalezisko/wpis) żeby je zobaczyć. Dodatkowe tapnięcie. Jak myślicie, czy można to zrobić jak na stronie www? Tj. wyświetlanie od razu miksu znaleziska + wpisy. Plus opcjonalne filtrowanie.

3. Po kliknięciu w trójkropek — ikona dodaj tag jako szybkie łącze ma ikonę odświeżania; sam tekst nie mieści się w oknie.

**Comment by CodoDodo** [comment]
1. Masz rację, dodaliśmy ukrywanie obrazka i opisów gdy ich nie ma.
2. Dodaliśmy taką listę, jest ona pobierana tak czy inaczej więc teraz też wyświetlają się od razu
3. Poprawione
