### ISSUE TITLE
Błąd odświeżania powiadomień 

### ISSUE THREAD

**Issue by RichForever** [CodoDodo/Zakop#78]
Z powiadomieniami dzieją się dziwne rzeczy. Gdy wejdę w ich listę i odświeżę to znikają mi wszystkie. Powrót do ustawień, wejście w powiadomienia i już są. Natomiast przy wejściu z dolnego paska pokazuje powiadomienia ale tylko raz. Więcej na filmiku

https://streamable.com/8l5mv

**Comment by CodoDodo** [comment]
Poprawione w wersji 12 - nie resetowaliśmy strony przy kasowaniu danych, stąd błąd (byłeś później domyślnie na drugiej, która była pusta)
