### ISSUE TITLE
Apka się wysypuje przy 3d touch

### ISSUE THREAD

**Issue by suqmadiq2ama** [CodoDodo/Zakop#8]
Jak docisne komentarz to wywala do ekranu startowego, swoją drogą fajnie by było zrobić tak plusowanie i minusowanie - przykładowo od połowy ekranu w lewo plus, w prawo minus

**Comment by CodoDodo** [comment]
Prawdopodobnie bug z wątku https://github.com/CodoDodo/Zakop/issues/16

A pomysł z 3d touch bardzo ciekawy, nie pomyśleliśmy o tym! Zapamiętamy go i zaproponujemy w wątku ze zmianami UI https://github.com/CodoDodo/Zakop/issues/20
