### ISSUE TITLE
Wczytywanie wpisów

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#82]
Czasem doświadczam błędu w oknie Mój Wykop polegający na tym, że po przesunięciu listy na sam koniec nie wczytują się kolejne wpisy. Nie wyświetla się spinner. Reset apki przywraca wszystko do normy.

**Comment by CodoDodo** [comment]
Wykop może ograniczać ilość pobieranych wpisów, wczytujemy tyle stron ile tylko możemy.
Ale faktycznie, był też błąd z zerowaniem na której stronie jesteśmy przez co po odświeżeniu mogły wpisy znikać lub się blokować. Poprawiliśmy tę część i poprawka będzie dostępna w wersji 12.

**Comment by CodoDodo** [comment]
@Cideu Gdyby błąd występował dalej po kolejnej aktualizacji, prosimy o nowy temat :-)
