### ISSUE TITLE
Błędne ikony przy wyborze czasu gorących

### ISSUE THREAD

**Issue by QuaLiTy132** [CodoDodo/Zakop#83]
Jak widać poniżej, przy wyborze czasu gorących ikony są pomieszane, "6" się dubluje", "12" jest 
przy 24 a "24" nie ma w ogóle.

![img_2368](https://user-images.githubusercontent.com/45571182/49390380-1736fe80-f729-11e8-90e8-c46107d565d3.png)

**Comment by CodoDodo** [comment]
Poprawione w wersji 12
