### ISSUE TITLE
Pulsowanie/odpowiadanie gestem

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#84]
Aktualny sposób plusowania i odpowiadania gestem na mikroblogu wydaje mi się teochę niewygodny. Trzeba przeciągnąć od prawej/lewej krawędzi aż do połowy ekranu aby złapało plusa/odpowiedź. 

Co myślicie o tym aby trochę zmniejszyć tę odległość przesunięcia palcem konkeczną do zapoczątkowania akcji?

**Comment by RichForever** [comment]
@Cideu wystarczy przesunąć odrobinę i opcja sama "wskakuje". Przynajmniej u mnie na X'ie tak jest

**Comment by Cideu** [comment]
@RichForever Mówisz o sytuacji, w której na wysunięte okno z pulsowaniem  trzeba dodatkowo tąpnąć. Mi chodzi o pulsowanie wyłącznie gestem przeciągnięcia

**Comment by CodoDodo** [comment]
@Cideu Jest to domyślna "animacja" z iOS i nie za bardzo da się cokolwiek w niej zmienić, niestety. Da się zrobić własne gesty od zera ale wymaga to dużo większej ilości pracy, więc może i zrobimy taką usprawnioną wersję ale w późniejszym czasie.

Na pocieszenie możemy dodać, że w kolejnej wersji aplikacji będzie opcja plusowania przez kliknięcie w plusy (tak samo z minusowaniem) :)
