### ISSUE TITLE
Pulsowanie usuniętych komentarzy  

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#85]
Na mirko jest mozwe pulsowanie komentarzy usuniętych. Zarówno gestem jak i z poziomu rozwijanego menu

**Comment by CodoDodo** [comment]
@Cideu Poprawione

**Comment by Cideu** [comment]
@CodoDodo problem nadal się pojawia, 
zaplusowane tąpnięciem 

https://imgur.com/a/hru4S8U
