### ISSUE TITLE
Usunięty komentarz

### ISSUE THREAD

**Issue by Cideu** [CodoDodo/Zakop#86]
Apka nie rozróżnia czy komentarz został usunięty przez autora komentarza, autora wpisu czy przez moderatora. Dla obu wyświetla łącznie tylko [komentarz usunięty]

**Comment by CodoDodo** [comment]
Niestety, ale Wykop informację o usunięciu komentarza zwraca tylko w jednej postaci i z tego co wiem, nie da się nic z tym zrobić :( @Cideu
