### ISSUE TITLE
Strona powitalna: Dużo separatorów

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#87]
Prio: Niski

Na iPadzie wygląda to słabo, że w sekcji „szybkie linki” jest tyle linii.
Na początku myślałam że jest to glitch albo błąd podczas ładowania tego ekranu.
![8da6a533-98ae-4c78-807a-93c73ff58508](https://user-images.githubusercontent.com/45828761/49888666-d8e3c280-fe3f-11e8-8831-eb400befe288.jpeg)

**Comment by CodoDodo** [comment]
To domyślne zachowanie iOS, zawsze rysuje te linie w dół gdy tabela się kończy.
Zobaczymy czy da się to ukryć

**Comment by CodoDodo** [comment]
Poprawione
