### ISSUE TITLE
Premium: Literówka

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#88]
Prio: Niski

Literówka :)
![59c1d854-b1d0-4ebb-b187-b3238aed6cc1](https://user-images.githubusercontent.com/45828761/49888778-22cca880-fe40-11e8-937b-8e3065e63482.jpeg)

**Comment by CodoDodo** [comment]
Niezłe masz oko ;-)
Poprawione! @Hannahalla
