### ISSUE TITLE
Premium: opcja „Przywróć”

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#89]
Prio: Niski

Pewnie jest to domyślne działanie okna ale jako użytkownik nie mam pojęcia czemu w oknie mówiącym o kupnie premium mam opcję „Przywróć” - ale co mam przywrócić? Wersję sprzed kupna? Jeszcze nie kupiłam premium to co mam przywracać : P 
![8037c810-2415-4389-9319-30d14c0b8c6d](https://user-images.githubusercontent.com/45828761/49888990-abe3df80-fe40-11e8-8b62-e707093c7333.jpeg)

**Comment by CodoDodo** [comment]
To też jedna z domyślnych funkcjonalności w iOS, dodatkowo wymagana i sprawdzana przez App Store. Chodzi tutaj o funkcję "Restore", która przywraca płatność zakupioną wcześniej lub na innym urządzeniu. W ten sposób gdy już płaciliśmy to nie musimy to robić drugi raz. 

Tak jak pisaliśmy, jest to sprawdzane przez App Store i każda aplikacja przy płatności ma ten przycisk gdzieś ukryty ;-)

**Comment by CodoDodo** [comment]
Poprawione :)
