### ISSUE TITLE
Filmy YT otwierają się w zewnętrznej aplikacji

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#90]
Prio: Normalny

Wpływa to na wygodę używania mirko. Przykład: wejdziesz we wpis typu „tu postujemy hity lat 90” i pod wpisem 100 piosenek. Jak dla każdej będzie mnie odsyłać do appki YT to szybko się zniechęcę do waszej appki.

**Comment by CodoDodo** [comment]
Na iOS jest ogólnie problem z obsługą YT ale postaramy się dodać taki odtwarzacz w ludzkiej formie

**Comment by CodoDodo** [comment]
@Hannahalla Dodane, co prawda nie jest idealnie ale jest i tak dużo lepiej niż było :)
Dodatek bedzie dostępny w kolejnym update.
