### ISSUE TITLE
Wpisy: info o ilości komentarzy nie trzyma się osi

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#91]
Prio: Normalny

Element o ilości komentarzy ma ustawioną sztywną odległość od daty dodania wpisu - wygląda to trochę niedbale.
![65d80c1a-b4eb-4609-8677-99b34e780922](https://user-images.githubusercontent.com/45828761/49889710-7fc95e00-fe42-11e8-8930-e633af582fb8.jpeg)

**Comment by CodoDodo** [comment]
Poprawione
