### ISSUE TITLE
Profil: brak liczby Zakopów i Odnaczeń

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#94]
Prio: Normalny

Słabo wygląda z powodu niespójności.
![07ee642a-3b2a-4901-a0b6-6a5fae72a425](https://user-images.githubusercontent.com/45828761/49889930-0e3ddf80-fe43-11e8-837b-458165b628e5.jpeg)

**Comment by CodoDodo** [comment]
@Hannahalla Tego niestety nie damy rady poprawić, Wykop nie daje nam informacji na temat ilości tych danych.
