### ISSUE TITLE
Powiadomienia: po tapnięciu avatara nie przechodzimy do profilu użytkownika

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#95]
Pomysł na feature

W „Powiadomieniach” gdy tapniemy na avatar - jesteśmy przenoszeni na profil danego użytkownika.

Do waszego przemyślenia czy jest sens to wprowadzać.

**Comment by CodoDodo** [comment]
Poprawione w tym momencie :)
