### ISSUE TITLE
Wpisy: brak podglądu kto plusował wpis/komentarz pod wpisem

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#96]
Prio: wysoki

Czasem istnieje potrzeba zawołać ludzi którzy plusowali nasz komentarz pod czyimś wpisem - nie ma do tego obecnie podglądu. Po tapnięciu w liczbę plusów mogłoby się pojawiać okno z listą.

**Comment by CodoDodo** [comment]
@Hannahalla Nie wiem czy jest to możliwe do zrobienia bo chcieliśmy już dodać listę plusujących ale znów - Wykop nie daje nam informacji o tym kto zaplusował dany wpis czy komentarz :(

**Comment by Hannahalla** [comment]
W wykopowej appce pokazujo to :(

**Comment by CodoDodo** [comment]
@Hannahalla Wiemy, ale to Wykop i oni nie stosują takich ograniczeń dla siebie ale dla innych już tak :( Ale mamy na to chytry pomysł i może uda nam się coś z tym zrobić :)

**Comment by CodoDodo** [comment]
@Hannahalla Jednak da się w łatwy sposób pobrać dane o plusujących, po prostu tego nie zauważyliśmy :) Dodane
