### ISSUE TITLE
Headery dolnego menu: odświeżenie po ponownym tapnięciu

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#97]
Pomysł na feature

Gdy jesteśmy na danej stronie, np. na „Mój Wykop”, tapnięcie na header menu „Mój Wykop” mogłoby spowodować odświeżenie strony.

**Comment by CodoDodo** [comment]
@Hannahalla Dodaliśmy przycisk odświeżania w obecnej wersji i będzie on dostępny w kolejnej aktualizacji :)
