### ISSUE TITLE
Znaleziska: opcja „udostępnij” crashuje appkę

### ISSUE THREAD

**Issue by Hannahalla** [CodoDodo/Zakop#99]
PRIO: BLOCKER

Tapnięcie „Udostępnij” wywala appkę na iPadzie.
![46803356-6f2e-4be0-bfb2-bc5641c3871f](https://user-images.githubusercontent.com/45828761/49892486-64158600-fe49-11e8-93a6-1acb80b5e398.jpeg)

**Comment by CodoDodo** [comment]
@Hannahalla Poprawione
